import { useMemo, useState, type CSSProperties } from "react";
import { ArrowRight, BookOpen, CalendarBlank, Check, CheckCircle, Clock, GitBranch, GraduationCap, House, Lock, MagnifyingGlass, MapTrifold, Minus, Plus, SlidersHorizontal, Sparkle, WarningCircle } from "@phosphor-icons/react";
import "./design-preview.css";

type Status = "completed" | "in-progress" | "planned" | "available" | "blocked" | "missing";
type Course = { code: string; title: string; units: number; status: Status; term: string; description: string; prereqs: string[]; unlocks: string[] };
const courseData: Course[] = [
  { code: "CMPE 30", title: "Programming Concepts and Methodology", units: 4, status: "completed", term: "Fall 2024", description: "Programming fundamentals, problem solving, and software development methodology.", prereqs: [], unlocks: ["CMPE 50"] },
  { code: "MATH 30", title: "Calculus I", units: 3, status: "completed", term: "Fall 2024", description: "Limits, differentiation, and applications for science and engineering.", prereqs: [], unlocks: ["MATH 31", "PHYS 50"] },
  { code: "CMPE 50", title: "Object-Oriented Concepts", units: 3, status: "in-progress", term: "Fall 2026", description: "Object-oriented design, data structures, and implementation techniques.", prereqs: ["CMPE 30"], unlocks: ["CMPE 126"] },
  { code: "MATH 31", title: "Calculus II", units: 4, status: "planned", term: "Spring 2027", description: "Integration, sequences, series, and applications of integral calculus.", prereqs: ["MATH 30"], unlocks: ["PHYS 51"] },
  { code: "PHYS 50", title: "General Physics: Mechanics", units: 4, status: "available", term: "Spring 2027", description: "Mechanics, oscillations, waves, and thermodynamics with laboratory work.", prereqs: ["MATH 30"], unlocks: ["PHYS 51"] },
  { code: "CMPE 126", title: "Algorithms and Data Structure Design", units: 3, status: "available", term: "Recommended next", description: "Design, analysis, and implementation of efficient algorithms and data structures.", prereqs: ["CMPE 50"], unlocks: ["CMPE 131"] },
  { code: "CMPE 131", title: "Software Engineering I", units: 3, status: "blocked", term: "Semester 5", description: "Requirements, architecture, testing, and team-based software delivery.", prereqs: ["CMPE 126"], unlocks: ["CMPE 195A"] },
  { code: "CMPE 124", title: "Digital Design I", units: 3, status: "missing", term: "Needs review", description: "Combinational and sequential digital systems with laboratory design.", prereqs: ["EE 98"], unlocks: ["CMPE 125"] },
];
const stateMap: Record<Status, { label: string; icon: typeof CheckCircle }> = {
  completed: { label: "Completed", icon: CheckCircle }, "in-progress": { label: "In progress", icon: Clock }, planned: { label: "Planned", icon: CalendarBlank }, available: { label: "Available", icon: Sparkle }, blocked: { label: "Blocked", icon: Lock }, missing: { label: "Missing prerequisite", icon: WarningCircle },
};
const edges = [
  { from: "CMPE 30", to: "CMPE 50", d: "M136 92 C136 136 136 140 136 178" }, { from: "MATH 30", to: "MATH 31", d: "M438 92 C438 136 438 140 438 178" }, { from: "MATH 30", to: "PHYS 50", d: "M438 92 C438 145 720 130 720 178" }, { from: "CMPE 50", to: "CMPE 126", d: "M136 270 C136 318 438 306 438 348" }, { from: "MATH 31", to: "CMPE 131", d: "M438 270 C438 314 720 306 720 348" }, { from: "CMPE 126", to: "CMPE 131", d: "M438 440 C438 476 720 474 720 518" },
];
function pathFor(code: string) { const included = new Set([code]); const up = (value: string) => edges.filter(edge => edge.to === value).forEach(edge => { if (!included.has(edge.from)) { included.add(edge.from); up(edge.from); } }); const down = (value: string) => edges.filter(edge => edge.from === value).forEach(edge => { if (!included.has(edge.to)) { included.add(edge.to); down(edge.to); } }); up(code); down(code); return included; }
function StatusTag({ status, tiny = false }: { status: Status; tiny?: boolean }) { const { label, icon: Icon } = stateMap[status]; return <span className={`cr-status cr-${status}${tiny ? " tiny" : ""}`}><Icon size={tiny ? 11 : 14} weight={status === "completed" ? "fill" : "regular"} />{label}</span>; }
function GraphNode({ course, selected, muted, onClick, slot }: { course: Course; selected: boolean; muted: boolean; onClick: () => void; slot: string }) { return <button className={`cr-node ${slot}${selected ? " selected" : ""}${muted ? " muted" : ""}`} onClick={onClick} aria-pressed={selected}><span className="cr-node-head"><strong>{course.code}</strong><span>{course.units} units</span></span><span className="cr-node-title">{course.title}</span><StatusTag status={course.status} tiny /></button>; }

export default function DesignPreview() {
  const [selectedCode, setSelectedCode] = useState("CMPE 126"); const [statusFilter, setStatusFilter] = useState<Status | "all">("all"); const [plannedCodes, setPlannedCodes] = useState(["MATH 31", "CMPE 126"]);
  const selected = courseData.find(course => course.code === selectedCode) ?? courseData[5]; const visiblePath = useMemo(() => pathFor(selectedCode), [selectedCode]); const graphCourses = courseData.slice(0, 7); const togglePlan = () => setPlannedCodes(current => current.includes(selected.code) ? current.filter(code => code !== selected.code) : [...current, selected.code]);
  return <div className="course-radar-preview">
    <header className="cr-header"><a className="cr-brand" href="#preview-top"><span className="cr-brand-orbit"><span /><i /></span><span>Course Radar<small>Plan with clarity</small></span></a><nav aria-label="Preview navigation"><a className="active" href="#preview-top"><House size={16} />Home</a><a href="#degree-map"><GitBranch size={16} />Degree map</a><a href="#semester-plan"><CalendarBlank size={16} />Plan</a><a href="#course-shelf"><BookOpen size={16} />Courses</a></nav><label className="cr-global-search"><MagnifyingGlass size={17} /><span className="cr-sr">Search courses</span><input placeholder="Search courses" /></label><button className="cr-avatar" aria-label="Open profile">TN</button></header>
    <main id="preview-top">
      <section className="cr-welcome"><div><span className="cr-overline">COMPUTER ENGINEERING · 2026–2027</span><h1>Good afternoon, Thinh.</h1><p>Your degree map is taking shape. Here’s what’s open now and what comes next.</p></div><div className="cr-degree-progress"><div className="cr-ring" style={{ "--progress": "62%" } as CSSProperties}><strong>62%</strong><span>complete</span></div><div><span>Degree progress</span><strong>74 / 120 units</strong><small>46 units to graduation</small></div><ArrowRight size={18} /></div></section>
      <section className="cr-map-section" id="degree-map"><div className="cr-section-title"><div><span className="cr-title-icon"><MapTrifold size={20} weight="duotone" /></span><div><h2>Your degree map</h2><p>Select a course to trace prerequisites and see what it unlocks.</p></div></div><div className="cr-map-actions"><label><MagnifyingGlass size={15} /><select aria-label="Focus course" value={selectedCode} onChange={event => setSelectedCode(event.target.value)}>{graphCourses.map(course => <option key={course.code}>{course.code}</option>)}</select></label><button aria-label="Map filters"><SlidersHorizontal size={17} /></button><span className="cr-zoom"><button aria-label="Zoom out"><Minus size={14} /></button><b>100%</b><button aria-label="Zoom in"><Plus size={14} /></button></span></div></div>
        <div className="cr-map-studio"><div className="cr-map-canvas"><div className="cr-map-legend"><span><i className="path" />Prerequisite path</span><span><i className="coreq" />Corequisite</span><span className="focus"><i />Focused on {selectedCode}</span></div><div className="cr-map-scroll"><div className="cr-map-inner"><svg className="cr-edges" viewBox="0 0 856 620" aria-hidden="true"><defs><marker id="cr-arrow" viewBox="0 0 8 8" refX="7" refY="4" markerWidth="6" markerHeight="6" orient="auto"><path d="M0 0L8 4L0 8Z" /></marker></defs>{edges.map(edge => <path key={`${edge.from}-${edge.to}`} d={edge.d} className={visiblePath.has(edge.from) && visiblePath.has(edge.to) ? "active" : "quiet"} />)}</svg>{graphCourses.map((course, index) => <GraphNode key={course.code} course={course} selected={selectedCode === course.code} muted={(statusFilter !== "all" && course.status !== statusFilter) || !visiblePath.has(course.code)} onClick={() => setSelectedCode(course.code)} slot={`slot-${index + 1}`} />)}</div></div><div className="cr-map-footer"><span>Course status</span>{(Object.keys(stateMap) as Status[]).map(status => <button key={status} className={statusFilter === status ? "active" : ""} onClick={() => setStatusFilter(statusFilter === status ? "all" : status)}><StatusTag status={status} tiny /></button>)}</div></div>
          <aside className="cr-inspector" aria-live="polite"><header><span>COURSE DETAILS</span><button aria-label="More course actions">•••</button></header><div className="cr-course-identity"><span className="cr-course-mark">{selected.code.split(" ")[0].slice(0, 2)}</span><div><strong>{selected.code}</strong><h3>{selected.title}</h3></div></div><StatusTag status={selected.status} /><dl><div><dt>Units</dt><dd>{selected.units}</dd></div><div><dt>Suggested</dt><dd>{selected.term}</dd></div></dl><section><h4>About</h4><p>{selected.description}</p></section><section><h4>Prerequisites</h4>{selected.prereqs.length ? selected.prereqs.map(code => <button className="cr-relation" key={code} onClick={() => courseData.some(course => course.code === code) && setSelectedCode(code)}><GitBranch size={15} /><span><strong>{code}</strong><small>Required before this course</small></span><ArrowRight size={14} /></button>) : <p className="cr-ready"><Check size={14} />No course prerequisite recorded</p>}</section><section><h4>Unlocks</h4><div className="cr-unlocks">{selected.unlocks.map(code => <button key={code} onClick={() => courseData.some(course => course.code === code) && setSelectedCode(code)}>{code}</button>)}</div></section><footer><button className="cr-outline" onClick={() => document.querySelector("#semester-plan")?.scrollIntoView({ behavior: "smooth" })}>View in planner</button><button className="cr-action" onClick={togglePlan}>{plannedCodes.includes(selected.code) ? <><Check size={15} />In your plan</> : <><Plus size={15} />Add to plan</>}</button></footer></aside></div>
      </section>
      <section className="cr-course-shelf" id="course-shelf"><div className="cr-section-title"><div><span className="cr-title-icon coral"><BookOpen size={20} /></span><div><h2>Courses on your radar</h2><p>Current, available, and planned courses at a glance.</p></div></div><button className="cr-link-button">Explore all courses <ArrowRight size={15} /></button></div><div className="cr-shelf-grid">{courseData.slice(2, 6).map(course => <button key={course.code} onClick={() => { setSelectedCode(course.code); document.querySelector("#degree-map")?.scrollIntoView({ behavior: "smooth" }); }}><span><strong>{course.code}</strong><small>{course.units} units</small></span><h3>{course.title}</h3><StatusTag status={course.status} tiny /><ArrowRight className="cr-card-arrow" size={17} /></button>)}</div></section>
      <section className="cr-planner" id="semester-plan"><div className="cr-section-title"><div><span className="cr-title-icon gold"><CalendarBlank size={20} /></span><div><h2>Semester plan</h2><p>A flexible draft for the year ahead.</p></div></div><button className="cr-link-button">Open full planner <ArrowRight size={15} /></button></div><div className="cr-term-grid"><article><header><div><span>FALL 2026</span><h3>In progress</h3></div><b>7 units</b></header><div className="cr-plan-course"><span>CMPE 50</span><strong>Object-Oriented Concepts</strong><StatusTag status="in-progress" tiny /></div><div className="cr-plan-course"><span>PHYS 50</span><strong>General Physics: Mechanics</strong><StatusTag status="available" tiny /></div><button className="cr-add-course"><Plus size={15} />Add course</button></article><article><header><div><span>SPRING 2027</span><h3>Next semester</h3></div><b>{plannedCodes.length * 3 + 1} units</b></header>{plannedCodes.slice(0, 3).map(code => { const course = courseData.find(item => item.code === code); return course ? <div className="cr-plan-course" key={code}><span>{course.code}</span><strong>{course.title}</strong><StatusTag status="planned" tiny /></div> : null; })}<button className="cr-add-course"><Plus size={15} />Add course</button></article><aside><GraduationCap size={25} weight="duotone" /><span>PLANNING NOTE</span><h3>You’re building toward upper-division standing.</h3><p>Finish the foundation sequence before adding advanced CMPE courses.</p><button>Review milestone <ArrowRight size={14} /></button></aside></div></section>
    </main><footer className="cr-footer"><span><span className="cr-mini-orbit" />Course Radar</span><p>Visual prototype · Static SJSU course data · Planning reference only</p></footer>
  </div>;
}
